import { defineConfig } from 'tsup'

export default defineConfig([
  // Node.js builds (CJS and ESM)
  {
    entry: ['src/index.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist',
    dts: true,
    clean: true,
    sourcemap: true,
    treeshake: true,
    target: 'node16',
    outExtension({ format }) {
      return {
        js: format === 'cjs' ? '.cjs' : '.mjs'
      }
    }
  },
  // Browser build (ESM only)
  {
    entry: ['src/index.ts'],
    format: ['esm'],
    outDir: 'dist',
    dts: false, // Already generated by Node build
    clean: false, // Don't clean, we want to keep Node builds
    sourcemap: true,
    treeshake: true,
    target: 'es2020',
    platform: 'browser',
    outExtension() {
      return {
        js: '.browser.mjs'
      }
    },
    esbuildOptions(options) {
      // Replace Node-specific globals with browser-compatible versions
      options.define = {
        'process.env.NODE_ENV': '"production"',
        global: 'globalThis'
      }
    }
  }
])
